# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trifle < Formula
  desc "CLI for Trifle time-series metrics"
  homepage "https://trifle.io"
  version "0.8.0"
  license "ELv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.8.0/trifle_0.8.0_darwin_amd64.tar.gz"
      sha256 "463601438f5c992852286474260f2538182e8ce57d06a5240e3adbdfda612843"

      define_method(:install) do
        bin.install "trifle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.8.0/trifle_0.8.0_darwin_arm64.tar.gz"
      sha256 "156ffa0772330a7a4a4c9bf9d59f1c6e0bd0a5af6fca91c5a92765a0187bd311"

      define_method(:install) do
        bin.install "trifle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.8.0/trifle_0.8.0_linux_amd64.tar.gz"
      sha256 "051ccadca693492875f795abac0fcebad0a728b12b97c14b00f9182d32d34030"
      define_method(:install) do
        bin.install "trifle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.8.0/trifle_0.8.0_linux_arm64.tar.gz"
      sha256 "a1a585c5d41cbf44b1c630d4be90c5286217f36841e95b274da89fbdd8cb0b06"
      define_method(:install) do
        bin.install "trifle"
      end
    end
  end

  test do
    system "#{bin}/trifle", "version"
  end
end
