# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trifle < Formula
  desc "CLI for Trifle time-series metrics"
  homepage "https://trifle.io"
  version "0.7.0"
  license "ELv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.7.0/trifle_0.7.0_darwin_amd64.tar.gz"
      sha256 "b3df76e58415ca40d7a55d3157049c47f04faa45b113f42f2178d11fc972971d"

      define_method(:install) do
        bin.install "trifle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.7.0/trifle_0.7.0_darwin_arm64.tar.gz"
      sha256 "d0cd91fcfe67937c13cb5d0b6cb370c0369a05036497b4da87a56a52ad52d1d7"

      define_method(:install) do
        bin.install "trifle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.7.0/trifle_0.7.0_linux_amd64.tar.gz"
      sha256 "727ba2b279c1843f992cbb804757256325f934b965e9a5360d6c4cc913443bdf"
      define_method(:install) do
        bin.install "trifle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.7.0/trifle_0.7.0_linux_arm64.tar.gz"
      sha256 "a3cad7517f889548e2548c525deedf10d1201e3cfbeecc39aa2e24b908903c45"
      define_method(:install) do
        bin.install "trifle"
      end
    end
  end

  test do
    system "#{bin}/trifle", "version"
  end
end
