# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trifle < Formula
  desc "CLI for Trifle time-series metrics"
  homepage "https://trifle.io"
  version "0.6.0"
  license "ELv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.6.0/trifle_0.6.0_darwin_amd64.tar.gz"
      sha256 "3fa4bb8ee42a6b105d79e2f7b7b8f239e3ecfccaa21c4c353e1ee9ce22460362"

      define_method(:install) do
        bin.install "trifle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.6.0/trifle_0.6.0_darwin_arm64.tar.gz"
      sha256 "a5c8f4c1ed691c551ed1213753ef508180c0cf863c1520f6f850fbad830a8245"

      define_method(:install) do
        bin.install "trifle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.6.0/trifle_0.6.0_linux_amd64.tar.gz"
      sha256 "47602ad11a29a1e497c7b363e260175dec05336f044c48acce09dbba18258a7c"
      define_method(:install) do
        bin.install "trifle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trifle-io/trifle-cli/releases/download/v0.6.0/trifle_0.6.0_linux_arm64.tar.gz"
      sha256 "3b7c03abd992a62eb4e66f793019d6502fa68df0b995c806d76d78f79630ba6d"
      define_method(:install) do
        bin.install "trifle"
      end
    end
  end

  test do
    system "#{bin}/trifle", "version"
  end
end
